# GitHub Actions metadata file
#
# @doc https://help.github.com/en/actions/building-actions/metadata-syntax-for-github-actions
#
name: github-actions-artillery
author: kenju
description: Load test your application with artillery/artillery
inputs:
  filepath:
    description: File path, relative to root directory, to the load test yaml
    required: true
    default: ./load-test.yml
outputs:
  report:
    description: A markdown string of the artillery report

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.filepath }}
branding: # Feather (https://feathericons.com/) icon
  icon: zap
  color: orange
